# Generated by Django 3.0.2 on 2020-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200121_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
