# Generated by Django 3.0.2 on 2020-01-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='order',
            field=models.IntegerField(),
        ),
    ]
