# Generated by Django 3.0.2 on 2020-01-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField(default=0)),
                ('success_rate', models.IntegerField(default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Record')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Test_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Result')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Test')),
            ],
        ),
    ]
