# Generated by Django 3.0.2 on 2020-01-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='average_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='success_rate',
            field=models.IntegerField(),
        ),
    ]
