# Generated by Django 3.0.2 on 2020-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20200127_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='success_rate',
            field=models.IntegerField(default=0),
        ),
    ]
