# Generated by Django 3.0.2 on 2020-01-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20200113_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='score.Record'),
        ),
        migrations.AlterField(
            model_name='test_score',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='score.Result'),
        ),
    ]
