# Generated by Django 3.0.2 on 2020-01-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_student',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_teacher',
            field=models.BooleanField(),
        ),
    ]
