//User authentication action types
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


//Subjects Action Types
export const GET_SUBJECTS_START = 'GET_SUBJECTS_START';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL';


//Create subject action types
export const CREATE_SUBJECT_START = 'CREATE_SUBJECT_START';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAIL = 'CREATE_SUBJECT_FAIL';


//Subject's tests action types
export const GET_SUBJECT_TESTS_START = 'GET_SUBJECT_TESTS_START';
export const GET_SUBJECT_TESTS_SUCCESS = 'GET_SUBJECT_TESTS_SUCCESS';
export const GET_SUBJECT_TESTS_FAIL = 'GET_SUBJECT_TESTS_FAIL';


//Subject's tests action types
export const GET_TEST_DETAILS_START = 'GET_TEST_DETAILS_START';
export const GET_TEST_DETAILS_SUCCESS = 'GET_TEST_DETAILS_SUCCESS';
export const GET_TEST_DETAILS_FAIL = 'GET_TEST_DETAILS_FAIL';


//Users Action Types
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

//Teachers Action Types
export const GET_TEACHERS_START = 'GET_TEACHERS_START';
export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS';
export const GET_TEACHERS_FAIL = 'GET_TEACHERS_FAIL';

//Students Action Types
export const GET_STUDENTS_START = 'GET_STUDENTS_START';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

//Records Action Types
export const GET_RECORDS_START = 'GET_RECORDS_START';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORDS_FAIL = 'GET_RECORDS_FAIL';

//Records Action Types
export const GET_RESULTS_START = 'GET_RESULTS_START';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAIL = 'GET_RESULTS_FAIL';

//Records Action Types
export const GET_RESULT_DETAILS_START = 'GET_RESULT_DETAILS_START';
export const GET_RESULT_DETAILS_SUCCESS = 'GET_RESULT_DETAILS_SUCCESS';
export const GET_RESULT_DETAILS_FAIL = 'GET_RESULT_DETAILS_FAIL';

//Submit test Action Types
export const SUBMIT_TEST_START = 'SUBMIT_TEST_START';
export const SUBMIT_TEST_SUCCESS = 'SUBMIT_TEST_SUCCESS';
export const SUBMIT_TEST_FAIL = 'SUBMIT_TEST_FAIL';


//Test scores Action Types
export const GET_TESTS_SCORES_START = 'GET_TESTS_SCORES_START';
export const GET_TESTS_SCORES_SUCCESS = 'GET_TESTS_SCORES_SUCCESS';
export const GET_TESTS_SCORES_FAIL = 'GET_TESTS_SCORES_FAIL';

