//User authentication action types
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


//Subjects Action Types
export const GET_SUBJECTS_START = 'GET_SUBJECTS_START';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL';


//Subject's tests action types
export const GET_SUBJECT_TESTS_START = 'GET_SUBJECT_TESTS_START';
export const GET_SUBJECT_TESTS_SUCCESS = 'GET_SUBJECT_TESTS_SUCCESS';
export const GET_SUBJECT_TESTS_FAIL = 'GET_SUBJECT_TESTS_FAIL';


//Users Action Types
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';


export const GET_TEACHERS_START = 'GET_TEACHERS_START';
export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS';
export const GET_TEACHERS_FAIL = 'GET_TEACHERS_FAIL';


export const GET_STUDENTS_START = 'GET_STUDENTS_START';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';